name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
  push:
    branches:
      - feat/devops

env:
  NODE_VERSION: 18.x
  PNPM_VERSION: 8

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ !contains(fromJSON('["frontend", "backend", "devops", "infrastructure"]'), github.event.pull_request.labels.name) }}
    steps:
      - name: message
        run: |
          echo "Required label '(frontend, backend, devops, infrastructure)' not found."
          exit 1

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4

      - name: Configure Worflow
        uses: ./.github/actions/configure

      - name: Build Project
        run: pnpm build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4

      - name: Configure Worflow
        uses: ./.github/actions/configure

      - name: Build Project
        run: pnpm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4

      - name: Configure Worflow
        uses: ./.github/actions/configure

      - name: Build Project
        run: pnpm lint

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure Worflow
        uses: ./.github/actions/configure

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
